max_retries: 3
development:
  concurrency: <%= ENV['WORKER_CONCURRENCY'] || '1' %>
playground:
  concurrency: <%= ENV['WORKER_CONCURRENCY'] || '1' %>
sandbox:
  concurrency: <%= ENV['WORKER_CONCURRENCY'] || '1' %>
production:
  concurrency: <%= ENV['WORKER_CONCURRENCY'] || '1' %>
queues:
  - [ai4cod_default, 1]
  - [ai4cod_mailer, 1]
  - [ai4cod_standard, 1]
  - [ai4cod_admin, 1]
