source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby ENV['RUBY_VERSION']

gem 'aws-sdk-cloudfront', '1.77'
gem 'bcrypt', '3.1.18'
gem 'bootsnap', '1.13.0', require: false
gem 'devise', '4.8.1'
gem 'devise-async', '1.0.0'
gem 'devise-i18n', '1.10.2'
gem 'enum_help', '0.0.19'
gem 'faraday', '2.6.0'
gem 'jbuilder', '2.11.5'
gem 'newrelic_rpm', '9.19.0'
gem 'paper_trail', '13.0.0'
gem 'pg', '1.4.3'
gem 'puma', '5.6.5'
gem 'pundit', '2.2.0'
gem 'rails', '7.0.4.3'
gem 'rails-i18n', '7.0.5'
gem 'redis', '4.8.0'
gem 'rswag-api', '2.7.0'
gem 'rswag-ui', '2.7.0'
gem 'sentry-rails', '5.9.0'
gem 'sentry-ruby', '5.9.0'
gem 'sidekiq', '6.5.7'
gem 'slim-rails', '3.5.1'
gem 'validates_timeliness', '7.0.0.beta1'
gem 'whenever', '1.0.0', require: false

group :production, :sandbox, :playground do
  gem 'activejob-traffic_control', '0.1.3', require: false
  gem 'rack-timeout', '0.6.3'
end

group :development, :test do
  gem 'byebug', '11.1.3'
  gem 'dotenv-rails', '2.8.1'
  gem 'rspec-rails', '5.1.2'
end

group :development do
  gem 'brakeman', '5.3.1', require: false
  gem 'letter_opener', '1.8.1'
  gem 'letter_opener_web', '2.0.0'
  gem 'rubocop', '1.37.0', require: false
  gem 'rubocop-rails', '2.17.0', require: false
  gem 'rubocop-rspec', '2.13.2', require: false
  gem 'web-console', '4.2.0'
end

group :test do
  gem 'factory_bot_rails', '6.2.0'
  gem 'faker', '3.2.0'
  gem 'i18n-spec', '0.6.0'
  gem 'rails-controller-testing', '1.0.5'
  gem 'rspec-json_expectations', '2.2.0'
  gem 'shoulda-matchers', '5.2.0'
  gem 'simplecov', '0.21.2', require: false
  gem 'timecop', '0.9.5'
end

gem 'aws-sdk-s3', '1.126.0'
