#!/bin/sh

set -e

. devops/compose/.env

ARG_LINUX_LOCALE=${ARG_LINUX_LOCALE} \
ARG_USER_UID=${ARG_USER_UID} \
ARG_USER_GID=${ARG_USER_GID} \
ARG_PLATFORM=${ARG_PLATFORM} \
ARG_RUBY_VERSION=${ARG_RUBY_VERSION} \
ARG_BUNDLER_VERSION=${ARG_BUNDLER_VERSION} \
DOCKER_DEFAULT_PLATFORM=${ARG_PLATFORM} \
  docker compose down --remove-orphans --volumes --rmi=all
